import { getContentType, unwrapMessage } from 'zapo-js';

import { getFirstStringAndRest, streamToBuffer, createThumbnailLink, downloadThumbnailLink, extractThumbnailFields } from '../helpers.js';
import { themeManager } from '../theme-manager.js';

const Emoji = Object.freeze({ SUCCESS: 'OK' });

const String = Object.freeze({ INVALID_SUBCOMMAND: 'invalid subcommand', TEXT_REQUIRE: 'masukkan teks', NO_SUBCOMMAND_1: `opsi tersedia:\n- title\n- description\n- url\n- thumbnail\n- export\n- use\n- preview (wip)`, SGC: `opsi tersedia\n- set <text>\n- get\n- clear`, URL: `opsi tersedia\n- set <urls>\n- get`, THUMB: `opsi tersedia\n- set <url>\n- set (reply ke image / thumbnail)\n- get` });
const checkUrl = url => { try { return new URL(url)?.toString(); } catch { return undefined; } };
const sanitizeFileName = s => s?.replaceAll(/[-./\\]+/g, '')?.match(/\S+/g)?.join('-');
const react = async ({ sock, jid, m }, emoji) => { try { await sock.message.send(jid, { type: 'reaction', emoji, target: m.key }); } catch (e) { console.error('[theme] gagal react:', e?.message ?? e); } };
const getImageFromMessage = async (sock, msg) => {
    try {
        const normalize = unwrapMessage(msg?.message ?? {}), ct = getContentType(normalize), media = normalize?.[ct];
        if ((ct === 'imageMessage' || ct === 'documentMessage') && media?.mimetype?.startsWith('image/')) { const stream = await sock.message.download(msg.message); const buffer = await streamToBuffer(stream); if (buffer?.length) return { buffer, mimetype: media.mimetype }; }
        if (ct === 'extendedTextMessage' && media?.mediaKey) { const fields = extractThumbnailFields({ extendedTextMessage: media }); if (fields) { const stream = await downloadThumbnailLink(fields); const buffer = await streamToBuffer(stream); if (buffer?.length) return { buffer, mimetype: fields.mimetype ?? 'image/jpeg' }; } }
    } catch (e) { console.error('gagal download image', e?.message ?? e); }
};
const resolveImageInput = async (ctx, param2) => {
    const { m, q, sock } = ctx, validUrl = checkUrl(param2); let validQuoted = false;
    if (q) { const normalize = unwrapMessage(q?.message ?? {}), ct = getContentType(normalize), mime = normalize?.[ct]?.mimetype; if ((ct === 'imageMessage' || ct === 'documentMessage') && mime?.startsWith('image/')) validQuoted = true; else if (ct === 'extendedTextMessage') validQuoted = Boolean(normalize?.extendedTextMessage?.mediaKey); }
    if (validUrl && validQuoted) return { error: 'gak boleh reply dan url' };
    if (validQuoted) { const got = await getImageFromMessage(sock, q); if (got?.buffer) return got; }
    else { const normalize = unwrapMessage(m?.message ?? {}), ct = getContentType(normalize), media = normalize?.[ct]; if ((ct === 'imageMessage' || ct === 'documentMessage') && media?.mimetype?.startsWith('image/')) { const got = await getImageFromMessage(sock, m); if (got?.buffer) return got; } else { if (!param2) return { error: 'isikan url atau reply ke sebuah gambar / thumbnail' }; if (!validUrl) return { error: 'invalid url' }; const response = await fetch(validUrl); if (!response.ok) return { error: `respond dari server ${response.status}` }; const ct2 = response.headers.get('content-type'); if (!ct2?.startsWith('image/')) return { error: `aku kurang yakin dengan content type ${ct2}. mungkin kamu bisa download gambarnya dulu baru set as thumbnail` }; return { buffer: Buffer.from(await response.arrayBuffer()), mimetype: ct2 }; } }
    return { error: 'gagal ambil gambar. coba pakai url atau upload gambar langsung' };
};
const handleTitle = async (ctx, sub, param) => { const { m } = ctx; if (sub === 'set') { if (!param) return await m.reply(String.TEXT_REQUIRE); const r = await themeManager.setTitle(param); if (r.error) return await m.reply(r.error); return await react(ctx, Emoji.SUCCESS); } if (sub === 'get') return await m.reply(themeManager.getData()?.title ?? '(title kosong)'); if (sub === 'clear') { const r = await themeManager.setTitle(undefined); if (r.error) return await m.reply(r.error); return await react(ctx, Emoji.SUCCESS); } return await m.reply(String.SGC); };
const handleDescription = async (ctx, sub, param) => { const { m } = ctx; if (sub === 'set') { if (!param) return await m.reply(String.TEXT_REQUIRE); const r = await themeManager.setDescription(param); if (r.error) return await m.reply(r.error); return await react(ctx, Emoji.SUCCESS); } if (sub === 'get') return await m.reply(themeManager.getData()?.description ?? '(description kosong)'); if (sub === 'clear') { const r = await themeManager.setDescription(undefined); if (r.error) return await m.reply(r.error); return await react(ctx, Emoji.SUCCESS); } return await m.reply(String.SGC); };
const handleUrl = async (ctx, sub, param) => { const { m } = ctx; if (sub === 'set') { const r = await themeManager.setUrl(param); if (r.error) return await m.reply(r.error); return await react(ctx, Emoji.SUCCESS); } if (sub === 'get') return await m.reply(themeManager.getData()?.url ?? '(url kosong)'); return await m.reply(String.URL); };
const handleThumbnail = async (ctx, sub, param) => { const { m, jid, sock } = ctx; if (sub === 'set') { const input = await resolveImageInput(ctx, param); if (input.error) return await m.reply(input.error); const wamc = await createThumbnailLink(sock, input.buffer, input.mimetype ?? 'image/jpeg'); const r = await themeManager.setMessage(wamc); if (r.error) return await m.reply(r.error); return await react(ctx, Emoji.SUCCESS); } if (sub === 'get') { const fields = extractThumbnailFields(themeManager.getData()?.message); if (!fields) return await m.reply('gak bisa download tamnel :v'); const stream = await downloadThumbnailLink(fields); return await sock.message.send(jid, { type: 'image', media: stream, mimetype: fields.mimetype ?? 'image/jpeg' }, { quote: m }); } if (sub === 'height') { const r = await themeManager.overrideHeightByRatio(param); if (r.error) return await m.reply(r.error); return await react(ctx, Emoji.SUCCESS); } if (sub === 'stock') { const r = await themeManager.setMessage(undefined); if (r.error) return await m.reply(r.error); return await m.reply(r.data); } return await m.reply(`command invalid opsi tersedia\n- set <url>\n- set <reply ke image, thumbnail, doc image>\n- set <upload image, thumbnail, doc image>\n- get\n- height <0.2 - 1>\n- stock`); };
const handleFavicon = async (ctx, sub, param) => { const { m, jid, sock } = ctx; if (sub === 'set') { const input = await resolveImageInput(ctx, param); if (input.error) return await m.reply(input.error); const wamc = await createThumbnailLink(sock, input.buffer, input.mimetype ?? 'image/jpeg'); const r = await themeManager.setFavicon(wamc); if (r.error) return await m.reply(r.error); return await react(ctx, Emoji.SUCCESS); } if (sub === 'get') { const favicon = themeManager.getData()?.message?.extendedTextMessage?.faviconMMSMetadata; if (!favicon?.mediaKey) return await m.reply('gak ada favicon. set dulu'); const stream = await downloadThumbnailLink({ directPath: favicon.thumbnailDirectPath, mediaKey: favicon.mediaKey, fileSha256: favicon.thumbnailSha256, fileEncSha256: favicon.thumbnailEncSha256 }); return await sock.message.send(jid, { type: 'image', media: stream, mimetype: 'image/jpeg' }, { quote: m }); } if (sub === 'clear') { const result = await themeManager.setFavicon(undefined); if (result?.error) return await m.reply(result.error); return await react(ctx, Emoji.SUCCESS); } return await m.reply(`opsi tersedia\n- set <url>\n- set <reply ke image, thumbnail, doc image>\n- set <upload image, thumbnail, doc image>\n- get\n- clear`); };
const handleExport = async (ctx, split1) => { const { jid, sock } = ctx; const data = JSON.stringify(themeManager.exportData(), null, 2); const prefixFileName = sanitizeFileName(split1?.restString) ?? 'theme'; const fileName = `${prefixFileName}-${Date.now()}.json`; return await sock.message.send(jid, { type: 'document', media: Buffer.from(data), fileName, mimetype: 'application/json', caption: 'nih :v' }); };
const handleUse = async ctx => { const { m, q, sock } = ctx; if (!q) return await m.reply('reply ke message, pastiin dokumen message json'); const qNormalized = unwrapMessage(q?.message), qContent = getContentType(qNormalized); if (qContent !== 'documentMessage') return await m.reply('musti dokumen message'); if (qNormalized?.documentMessage?.mimetype !== 'application/json') return await m.reply('gak mau mime nya kurang meyakinkan'); try { const stream = await sock.message.download(q.message), text = (await streamToBuffer(stream)).toString('utf8'), json = JSON.parse(text), r = await themeManager.useExternalJson(json); if (r?.error) return await m.reply(r.error); return await m.reply('sip theme berhasil di ganti. coba test'); } catch (e) { return await m.reply(`gagal use theme ${e?.message ?? e}`); } };
const run = async ctx => { const { m, text } = ctx, split1 = getFirstStringAndRest(text), split2 = getFirstStringAndRest(split1.restString), sub = split1.firstString, sub2 = split2.firstString, param = split2?.restString?.substring(1); if (!sub) return await m.reply(String.NO_SUBCOMMAND_1); if (sub === 'title') return await handleTitle(ctx, sub2, param); if (sub === 'desc' || sub === 'description') return await handleDescription(ctx, sub2, param); if (sub === 'url') return await handleUrl(ctx, sub2, param); if (sub === 'thumb' || sub === 'thumbnail') return await handleThumbnail(ctx, sub2, param); if (sub === 'fav' || sub === 'favicon') return await handleFavicon(ctx, sub2, param); if (sub === 'export') return await handleExport(ctx, split1); if (sub === 'use') return await handleUse(ctx); if (sub === 'preview') return await m.reply('masih di buat'); return await m.reply(String.INVALID_SUBCOMMAND); };

const plugin = { run, name: 'theme manager', command: ['theme'], description: 'buat ubah title, description, thumbnail, url. dll. malas jelasin coba aja langsung panggil command nya :v', ownerOnly: true, category: ['core'] };
export default plugin;
